version: 0.2

env:
  variables:
    PRODUCT: devsecops
    APPNAME: appsec
    PACKAGE: github.com/hashishrajan/cognito-vue-oauth2-demo
    SEVERITY_DEFAULT_THRESHOLD: 5

phases:
  install:
    commands:
      - apt-get update && apt-get install gettext-base
      - env | sort
      - pwd
      # Starting dir location
      - mkdir -p "/appsec/$(dirname ${PACKAGE})"
      - echo "/appsec/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/appsec/${PACKAGE}"
      - cd "/appsec/${PACKAGE}"
      - npm version
      - npm install -i -g nsp nsp-reporter-checkstyle
  pre_build:
    commands:
      - cd "/appsec/${PACKAGE}"
      # Debugging
      - pwd
  build:
    commands:
      - cd "/appsec/${PACKAGE}"
      - pwd
      - npm i
      - nsp check --reporter checkstyle
      - if ['echo $?'==0]; then echo "Success" else echo "Investigate"
